import type { Metadata } from "next";
import React from "react";
import localFont from "next/font/local";
import "./globals.css";
import SystemProvider from "@/components/SystemProvider";
import QueryProvider from "@/components/QueryProvider";
import { Toaster } from "@/components/ui/sonner";
import LoginModal from "@/components/modal/LoginModal";

const myFont = localFont({
  src: "./PretendardVariable.woff2",
  display: "swap",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={"dark"}>
      <body className={`${myFont.className} bg-background text-foreground`}>
        <SystemProvider>
          <Toaster />
          <QueryProvider>
            {children}
            <LoginModal />
          </QueryProvider>
        </SystemProvider>
      </body>
    </html>
  );
}
