import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import SystemProvider from "@/components/SystemProvider";
import QueryProvider from "@/components/QueryProvider";
import { Toaster } from "@/components/ui/sonner";
import LoginModal from "@/components/modal/LoginModal";
import { notoSansKR, pretendard } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={"dark"}>
      <body
        className={`${pretendard.variable} ${notoSansKR.className} bg-background text-foreground`}
      >
        <SystemProvider>
          <Toaster />
          <QueryProvider>
            {children}
            <LoginModal />
          </QueryProvider>
        </SystemProvider>
      </body>
    </html>
  );
}
