import type { Metadata } from "next";
import React from "react";
import localFont from "next/font/local";
import "./globals.css";
import SystemProvider from "@/components/SystemProvider";
import { ThemeProvider } from "@/components/ThemeProvider";

const myFont = localFont({
  src: "./PretendardVariable.woff2",
  display: "swap",
  variable: "--font-Pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={"dark"}>
      <body className={`${myFont.className} bg-background text-foreground`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SystemProvider>{children}</SystemProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
